// <auto-generated />
using System;
using DocSmith.Pulse.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocSmith.Pulse.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PulseDbContext))]
    partial class PulseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DocSmith.Pulse.Core.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActivityAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Clicks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Comments")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContentIdeaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EngagementTargetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Impressions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Reactions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityAtUtc");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("DocSmith.Pulse.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasBlocked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DocSmith.Pulse.Core.Entities.BrandVoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvoidEmojis")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvoidFearMarketing")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForbiddenClaimsCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToneRules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BrandVoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvoidEmojis = true,
                            AvoidFearMarketing = true,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ForbiddenClaimsCsv = "guaranteed,official,MoHRE approved",
                            IsDefault = true,
                            Name = "DocSmith Professional",
                            Persona = "SME Founder",
                            ToneRules = "Authoritative, compliance-aware, practical, concise."
                        });
                });

            modelBuilder.Entity("DocSmith.Pulse.Core.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndsOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartsOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("DocSmith.Pulse.Core.Entities.ContentDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentIdeaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hashtags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VariantNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentIdeaId", "VariantNo", "Channel")
                        .IsUnique();

                    b.ToTable("ContentDrafts");
                });

            modelBuilder.Entity("DocSmith.Pulse.Core.Entities.ContentIdea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CtaStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledForUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ScheduledForUtc");

                    b.HasIndex("Status");

                    b.ToTable("ContentIdeas");
                });

            modelBuilder.Entity("DocSmith.Pulse.Core.Entities.EngagementTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftCommentMedium")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftCommentShort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("EngagementTargets");
                });

            modelBuilder.Entity("DocSmith.Pulse.Core.Entities.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaAssetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("DocSmith.Pulse.Core.Entities.SafetyState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AiGenerationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExportsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GlobalKillSwitchEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OrganizationSafeModeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SchedulerEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SafetyStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AiGenerationEnabled = false,
                            ExportsEnabled = true,
                            GlobalKillSwitchEnabled = false,
                            OrganizationSafeModeEnabled = true,
                            SchedulerEnabled = false,
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DocSmith.Pulse.Core.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Prime",
                            Email = ""
                        });
                });

            modelBuilder.Entity("DocSmith.Pulse.Core.Entities.ContentDraft", b =>
                {
                    b.HasOne("DocSmith.Pulse.Core.Entities.ContentIdea", "ContentIdea")
                        .WithMany()
                        .HasForeignKey("ContentIdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentIdea");
                });

            modelBuilder.Entity("DocSmith.Pulse.Core.Entities.ContentIdea", b =>
                {
                    b.HasOne("DocSmith.Pulse.Core.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campaign");
                });
#pragma warning restore 612, 618
        }
    }
}
