// <auto-generated />
using System;
using DocSmith.Pulse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocSmith.Pulse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212205808_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DocSmith.Pulse.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActivityAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Clicks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Comments")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Impressions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Reactions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityAtUtc");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("DocSmith.Pulse.Models.EngagementTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftCommentMedium")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftCommentShort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("EngagementTargets");
                });

            modelBuilder.Entity("DocSmith.Pulse.Models.PostDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hashtags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostIdeaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VariantNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostIdeaId", "VariantNo")
                        .IsUnique();

                    b.ToTable("PostDrafts");
                });

            modelBuilder.Entity("DocSmith.Pulse.Models.PostIdea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CtaStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("PostIdeas");
                });

            modelBuilder.Entity("DocSmith.Pulse.Models.PostDraft", b =>
                {
                    b.HasOne("DocSmith.Pulse.Models.PostIdea", "PostIdea")
                        .WithMany()
                        .HasForeignKey("PostIdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostIdea");
                });
#pragma warning restore 612, 618
        }
    }
}
